#!/bin/sh
for i in 1 2 3 4 5 6; do
  gsleep .6 && echo   0 > /sys/class/leds/lp5523:kb${i}/brightness
  gsleep .5 && echo 255 > /sys/class/leds/lp5523:kb${i}/brightness
  gsleep .5 && echo   0 > /sys/class/leds/lp5523:kb${i}/brightness
  gsleep .6 && echo 255 > /sys/class/leds/lp5523:kb${i}/brightness
done
